# Generated by Django 4.0.4 on 2022-04-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='product',
            new_name='super_type',
        ),
    ]
